#!/bin/bash

set -euo pipefail

xcodebuild docbuild \
  -scheme SafariUI \
  -destination "platform=iOS Simulator,OS=18.4,name=iPhone 16 Pro" \
  -derivedDataPath docs

docc process-archive transform-for-static-hosting \
  --hosting-base-path SafariUI/docs \
  --output-path docs/html \
  docs/Build/Products/Debug-iphoneos/SafariUI.doccarchive