#!/bin/bash

swift package --allow-writing-to-directory docs \
    generate-documentation --target SafariUI \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path SafaiUI/docs \
    --output-path docs