name: Create Release Artifacts
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-docc-archive:
    runs-on: macos-15
    outputs:
      artifact-name: archive
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Xcode Version
        run: ./.scripts/xcode-select
      - name: Build Documentation
        run: |
          xcodebuild docbuild \
            -scheme SafariUI \
            -destination "platform=iOS Simulator,OS=18.4,name=iPhone 16 Pro" \
            -sdk iphonesimulator \
            -derivedDataPath docs
      - name: Compress DocC Archive
        run: |
          cd docs/Build/Products/Debug-iphonesimulator
          zip -r SafariUI.doccarchive.zip SafariUI.doccarchive
      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: docs/Build/Products/Debug-iphonesimulator/SafariUI.doccarchive.zip
  attach-archive:
    needs: build-docc-archive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download DocC Archive
        uses: actions/download-artifact@v4
        with:
          name: archive
          path: .
      - name: Attach DocC Archive to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./SafariUI.doccarchive.zip